# Generated by Django 5.1.15 on 2026-06-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('salary', 'Salary'), ('business', 'Business Income'), ('transfer', 'Transfer'), ('other', 'Other')], max_length=20)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('goal_type', models.CharField(choices=[('general', 'General savings'), ('emergency', 'Emergency fund'), ('travel', 'Travel'), ('business', 'Business'), ('education', 'Education'), ('electronics', 'Electronics'), ('property', 'Property')], default='general', max_length=12)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('in', 'Income'), ('out', 'Expense')], max_length=3)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('salary', 'Salary'), ('business', 'Business Income'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('source_type', models.CharField(choices=[('mpesa_sms', 'M-Pesa SMS'), ('bank_sms', 'Bank SMS'), ('manual', 'Manual'), ('receipt', 'Receipt Scan'), ('chat', 'Hela AI')], default='manual', max_length=12)),
                ('source_institution', models.CharField(blank=True, max_length=40)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sms_fingerprint', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sms_fingerprint', ''), _negated=True), fields=('user', 'sms_fingerprint'), name='unique_user_sms_fingerprint')],
            },
        ),
    ]
